
["Feature Options"]

	["Feature Options".Structures]
		#
		# How often small ruined buildings made of end stone will generate in the end.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare abandoned end houses
		#Range: 10 ~ 10000
		abandonedEndHouseSpawnrate = 50
		#
		# How often barns will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# The barn is around a chunk in length, so lowering this too much can make barns more likely to collide.
		# 5 to practically always have several near each village, 10000 for extremely rare barns
		#Range: 5 ~ 10000
		barnSpawnrate = 10
		#
		# How often towers will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare towers
		#Range: 10 ~ 10000
		towerSpawnrate = 20
		#
		# How often red sandstone wells will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare red sandstone wells
		#Range: 10 ~ 10000
		redSandstoneWellSpawnrate = 20
		#
		# How often small mushrooms with a vase and a sign saying 'Drink Me' will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare drink me mushroom
		#Range: 10 ~ 10000
		drinkMeMushroomSpawnrate = 20
		#
		# How often coarse dirt huts will spawn in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare abandoned end houses
		#Range: 10 ~ 10000
		dangerousDirtHutSpawnrate = 40
		#
		# Whether or not to spawn yakhchals, ancient buildings designed to use wind to keep ice frozen, in desert biomes
		# Default value is true
		yakhchalCanSpawn = true
		#
		# Whether or not to spawn towers in hills and mountains
		# Default value is true
		towerCanSpawn = true
		#
		# How often yakhchals will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare yakhchals
		#Range: 10 ~ 10000
		yakhchalSpawnrate = 23
		#
		# How often ruined nether portals surrounded by nether blocks will attempt to spawn per chunk in valid biomes.
		# The config value is the max distance in chunks between spawn attempts, but not all spawn attempts will succeed.
		# 10 to practically always have one in render distance, 10000 for extremely rare red sandstone wells
		#Range: 10 ~ 10000
		leakingNetherPortalRuinSpawnrate = 40
		#
		# Whether or not to spawn barns near villages
		# Default value is true
		barnCanSpawn = true

